server:
  port: 8000
  servlet:
    context-path: /business-tier
  ssl:
    enabled: true
    key-alias: bt
    key-store-password: changeit
    key-store-type: pkcs12
    key-store: classpath:security/bt.p12

spring:
  datasource:
    user-ds:
      jndi-name: java:comp/env/jdbc/userds
    book-ds:
      jndi-name: java:comp/env/jdbc/bookds
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
