server:
  port: 8180
  servlet:
    context-path: /demo
#  tomcat:
#    remoteip:
#      host-header: x-forwarded-for
#      protocol-header: x-forwarded-proto

business-tier:
  url : https://localhost:8000/business-tier

ssl:
  custom:
    trust-store: classpath:security/truststore/bt.p12
    trust-store-password: changeit

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

